packages:
  - apps/*
  - '!apps/mobile'
  - '!apps/receiver'
  - services/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - edgedriver
  - electron
  - esbuild
  - geckodriver
  - prisma
  - tesseract.js
