"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.updateSettings = exports.getSettings = exports.touchSwipe = exports.touchTap = exports.activateApp = exports.windowSize = exports.setElementValue = exports.elementCenter = exports.elementRect = exports.elementAttribute = exports.elementText = exports.tapElement = exports.elementId = exports.findFirst = exports.findElements = exports.pressButton = exports.source = exports.screenshot = exports.typeText = exports.swipe = exports.tap = exports.go_home = exports.status = void 0;
// 原子操作 barrel。
var status_1 = require("./status");
Object.defineProperty(exports, "status", { enumerable: true, get: function () { return __importDefault(status_1).default; } });
var go_home_1 = require("./go_home");
Object.defineProperty(exports, "go_home", { enumerable: true, get: function () { return __importDefault(go_home_1).default; } });
var tap_1 = require("./tap");
Object.defineProperty(exports, "tap", { enumerable: true, get: function () { return __importDefault(tap_1).default; } });
var swipe_1 = require("./swipe");
Object.defineProperty(exports, "swipe", { enumerable: true, get: function () { return __importDefault(swipe_1).default; } });
var typeText_1 = require("./typeText");
Object.defineProperty(exports, "typeText", { enumerable: true, get: function () { return __importDefault(typeText_1).default; } });
var screenshot_1 = require("./screenshot");
Object.defineProperty(exports, "screenshot", { enumerable: true, get: function () { return __importDefault(screenshot_1).default; } });
var source_1 = require("./source");
Object.defineProperty(exports, "source", { enumerable: true, get: function () { return __importDefault(source_1).default; } });
var pressButton_1 = require("./pressButton");
Object.defineProperty(exports, "pressButton", { enumerable: true, get: function () { return __importDefault(pressButton_1).default; } });
var findElements_1 = require("./findElements");
Object.defineProperty(exports, "findElements", { enumerable: true, get: function () { return findElements_1.findElements; } });
Object.defineProperty(exports, "findFirst", { enumerable: true, get: function () { return findElements_1.findFirst; } });
Object.defineProperty(exports, "elementId", { enumerable: true, get: function () { return findElements_1.elementId; } });
var element_1 = require("./element");
Object.defineProperty(exports, "tapElement", { enumerable: true, get: function () { return element_1.tapElement; } });
Object.defineProperty(exports, "elementText", { enumerable: true, get: function () { return element_1.elementText; } });
Object.defineProperty(exports, "elementAttribute", { enumerable: true, get: function () { return element_1.elementAttribute; } });
Object.defineProperty(exports, "elementRect", { enumerable: true, get: function () { return element_1.elementRect; } });
Object.defineProperty(exports, "elementCenter", { enumerable: true, get: function () { return element_1.elementCenter; } });
Object.defineProperty(exports, "setElementValue", { enumerable: true, get: function () { return element_1.setElementValue; } });
var window_1 = require("./window");
Object.defineProperty(exports, "windowSize", { enumerable: true, get: function () { return window_1.windowSize; } });
var activateApp_1 = require("./activateApp");
Object.defineProperty(exports, "activateApp", { enumerable: true, get: function () { return activateApp_1.activateApp; } });
var touchPerform_1 = require("./touchPerform");
Object.defineProperty(exports, "touchTap", { enumerable: true, get: function () { return touchPerform_1.touchTap; } });
Object.defineProperty(exports, "touchSwipe", { enumerable: true, get: function () { return touchPerform_1.touchSwipe; } });
var settings_1 = require("./settings");
Object.defineProperty(exports, "getSettings", { enumerable: true, get: function () { return settings_1.getSettings; } });
Object.defineProperty(exports, "updateSettings", { enumerable: true, get: function () { return settings_1.updateSettings; } });
